version: '3'
services:
  presto:
    hostname: presto
    image: 'prestosql/presto:334'
    container_name: presto
    ports:
      - '8080:8080'
    volumes: 
      - './presto/minio.properties:/usr/lib/presto/etc/catalog/minio.properties'
      - './presto/node.properties:/usr/lib/presto/etc/node.properties'
      - './presto/config.properties:/usr/lib/presto/etc/config.properties'
      - './presto/log.properties:/usr/lib/presto/etc/log.properties'
      - './presto/jvm.config:/usr/lib/presto/etc/jvm.config'
      - './hadoop/lib/json-serde-1.3.8-jar-with-dependencies.jar:/usr/lib/presto/plugin/hive-hadoop2/json-serde-1.3.8-jar-with-dependencies.jar'

  hive-metastore:
    build: hive/.
    image: hive-metastore
    restart: always
    links:
      - "minio"
    depends_on:
      - "postgres"
    ports:
      - 9083:9083
      - 10000:10000
      - 10002:10002
    healthcheck:
      test: "netstat -lpn | grep 9083"
      interval: 30s
      retries: 5

  postgres:
    image: postgres:9.6.10
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: hivemetastore
      POSTGRES_USER: hivemetastore
      POSTGRES_PASSWORD: hivemetastore
    ports: 
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "psql -h localhost -U hivemetastore -c 'select 1' hivemetastore"
      interval: 1m
      retries: 5

  minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - './minio/data/:/data'
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    command: server /data

volumes: 
  postgres-data: